### ISSUE TITLE
Add Ivy Glioblastoma Atlas Project dataset to AWS open dataset registry

### ISSUE THREAD

**Issue by njmei** [AllenInstitute/open_dataset_tools#2]
The IVY GAP dataset is not currently on the AWS open dataset registry, we should at some point add it:

https://registry.opendata.aws/

Allen Mouse Brain Atlas is findable in the registry:
https://registry.opendata.aws/allen-mouse-brain-atlas/

Open questions:
- Do we need to coordinate with communications?

**Comment by wbwakeman** [comment]
A YAML file for this project is here:
/allen/aibs/technology/waynew/allen-ivy-glioblastoma-atlas.yaml

**Comment by wbwakeman** [comment]
>Do we need to coordinate with communications?

Yes, I have been in touch with them.  We are targeting July 15 for a Twitter push to coincide with the AWS press release.  The work to add this YAML file to https://github.com/awslabs/open-data-registry can be done at any time and should be done well in advance of that date.

**Comment by njmei** [comment]
PR has been created:
https://github.com/awslabs/open-data-registry/pull/1035
- [x] Waiting on approval and merge

**Comment by njmei** [comment]
Okay this looks to be done now!
